version: '3.9'

services:
  db:
    image: clickhouse/clickhouse-server:latest
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123/"]
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.docker/clickhouse:/var/lib/clickhouse/
      - ./.docker/clickhouse-server:/var/lib/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: defaultdb
      CLICKHOUSE_USER: secretuser
      CLICKHOUSE_PASSWORD: mysecretpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    restart: unless-stopped
    networks:
        - insights
#  app:
#    image: instant-insights:latest
#    depends_on:
#      - db
#    ports:
#      - "3000:3000"
#    environment:
#      CLICKHOUSE_NAME: default
#      CLICKHOUSE_URL: 'http://db:8123'
#      CLICKHOUSE_USER: secretuser
#      CLICKHOUSE_PASS: mysecretpassword
#      CLICKHOUSE_CONNECT_TIMEOUT: 10000
#      CLICKHOUSE_REQUEST_TIMEOUT: 30000
#      CLICKHOUSE_MAX_OPEN_CONNECTIONS: 0
#      CRON_INSERT_PATTERN: '* * * * * *'
#      DISCARD_EVENTS_ON_INSERT_ERROR: true
#      MAX_EVENT_SIZE: 1KB
#      ONLINE_TIMESPAN: 5
#      API_WRITE_TOKEN: '1a2acdb9-b51e-4658-ab8e-c015a464362b'
#      BACKUP_TO_S3_ENABLE: false
#      BACKUP_TO_S3_URL: ''
#      BACKUP_TO_S3_ACCESS_KEY: ''
#      BACKUP_TO_S3_SECRET_KEY: ''
#      BACKUP_TO_S3_CRON_PATTERN: '0 0 */1 * *'
#      JWT_SECRET: 'secret'
#      TOKEN_EXPIRE_IN: 86400
#      REFRESH_TOKEN_EXPIRE_IN: 604800
#      USER_EMAIL: 'admin@localhost'
#      USER_PASSWORD: '22486ec7-a3ec-4d9e-80d4-ecea8bc58bb2'
#    networks:
#        - insights
networks:
    insights:
      attachable: true