version: '3.9'

services:
  db:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./.docker/clickhouse:/var/lib/clickhouse/
      - ./.docker/clickhouse-server:/var/lib/clickhouse-server/
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      CLICKHOUSE_DB: insights
      CLICKHOUSE_USER: secretuser
      CLICKHOUSE_PASSWORD: mysecretpassword
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
